version: "3"
services:
  jupyter:
    build:
      context: ./jupyter
    ports:
      - "8888:8888"
    links:
      - postgres
    volumes:
      - "./notebooks:/notebooks"
      - "./data:/data"

  postgres:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: data
      POSTGRES_PASSWORD: data
      POSTGRES_DB: data
    volumes:
      - ./infra/create_tables.sql:/docker-entrypoint-initdb.d/create_tables.sql